export { default as About } from './About/About'
export { default as Home } from './Home/Home'
export { default as Login, ForgotPassword, ResetPassword } from './Login'
export { default as Logout } from './Logout'
export { default as NotFound } from './NotFound/NotFound'
export { default as SignUp, ResendConfirmation, PendingConfirmation } from './SignUp'
export { default as Styles } from './Styles/Styles'
export { default as Protected } from './Protected/Protected'
export { default as Profile } from './Profile'
