"""
create blog models

Revision ID: 65c9668d1396
Revises: 
Create Date: 2017-10-11 17:47:12.712133
"""

from alembic import op
import sqlalchemy as sa


import backend

# revision identifiers, used by Alembic.
revision = '65c9668d1396'
down_revision = None
branch_labels = ('blog',)
depends_on = '8036f244db77'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category'))
    )
    op.create_table('tag',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag'))
    )
    op.create_table('series',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('header_image', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_series_category_id_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series'))
    )
    op.create_table('series_article',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('part', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_series_article_series_id_series')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series_article'))
    )
    op.create_table('series_tag',
    sa.Column('series_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_series_tag_series_id_series')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_series_tag_tag_id_tag')),
    sa.PrimaryKeyConstraint('series_id', 'tag_id', name=op.f('pk_series_tag'))
    )
    op.create_table('article',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', backend.database.types.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('publish_date', backend.database.types.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', backend.database.types.DateTime(timezone=True), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('header_image', sa.String(length=255), nullable=True),
    sa.Column('preview', sa.Text(), nullable=False),
    sa.Column('html', sa.Text(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('article_series_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['article_series_id'], ['series_article.id'], name=op.f('fk_article_article_series_id_series_article')),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], name=op.f('fk_article_author_id_user')),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name=op.f('fk_article_category_id_category')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_article'))
    )
    op.create_table('article_tag',
    sa.Column('article_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], name=op.f('fk_article_tag_article_id_article')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_article_tag_tag_id_tag')),
    sa.PrimaryKeyConstraint('article_id', 'tag_id', name=op.f('pk_article_tag'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_tag')
    op.drop_table('article')
    op.drop_table('series_tag')
    op.drop_table('series_article')
    op.drop_table('series')
    op.drop_table('tag')
    op.drop_table('category')
    # ### end Alembic commands ###
