"""empty message

Revision ID: 4169dd7a0e6b
Revises: b4f18f29686e
Create Date: 2017-10-04 19:59:42.109835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4169dd7a0e6b'
down_revision = 'b4f18f29686e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=64), nullable=True))
        batch_op.alter_column('first_name', existing_type=sa.VARCHAR(length=32), nullable=False)
        batch_op.alter_column('last_name', existing_type=sa.VARCHAR(length=64), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
